/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.prop.presentacio;

import java.awt.Cursor;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author mati
 */
public class Partida extends javax.swing.JFrame {
    
    private ControladorDePresentacio p = new ControladorDePresentacio();
    private String selectedColor = "/images/empty.png";
    private int selectedInt = 0;
    private int editable = 0;
    private int[] codi = new int[4];
    
    private ArrayList<JLabel> res0;
    private ArrayList<JLabel> res1;
    private ArrayList<JLabel> res2;
    private ArrayList<JLabel> res3;
    private ArrayList<JLabel> res4;
    private ArrayList<JLabel> res5;
    private ArrayList<JLabel> res6;
    private ArrayList<JLabel> res7;
    private ArrayList<JLabel> res8;
    private ArrayList<ArrayList<JLabel>> respostes;
    
    private ArrayList<JButton> comb0;
    private ArrayList<JButton> comb1;
    private ArrayList<JButton> comb2;
    private ArrayList<JButton> comb3;
    private ArrayList<JButton> comb4;
    private ArrayList<JButton> comb5;
    private ArrayList<JButton> comb6;
    private ArrayList<JButton> comb7;
    private ArrayList<JButton> comb8;
    private ArrayList<ArrayList<JButton>> combinacions;

    /**
     * Creates new form VistaTauler
     */
    public Partida() {
        editable = 0;
        
        initComponents();
        
        ferGrupsRespostes();
        ferGrupsCombinacions();
        
        p.controller.setTauler(this);
        //if (p.controller.esCodeMaker()) {
           // Controles.setVisible(false);
           // btnCheck.setVisible(false);
           // txtColores.setVisible(false);
            
            ArrayList<String> sols = p.controller.getSolucio();
            sol0.setIcon(new javax.swing.ImageIcon(getClass().getResource(sols.get(0))));
            sol1.setIcon(new javax.swing.ImageIcon(getClass().getResource(sols.get(1))));
            sol2.setIcon(new javax.swing.ImageIcon(getClass().getResource(sols.get(2))));
            sol3.setIcon(new javax.swing.ImageIcon(getClass().getResource(sols.get(3))));
            
            //p.controller.jugaCodeMaker();
        //} else {
//            Controles.setVisible(true);
//            btnCheck.setVisible(true);
//            txtColores.setVisible(true);
//            
//            sol0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png")));
//            sol1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png")));
//            sol2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png")));
//            sol3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png")));
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Controles = new javax.swing.JPanel();
        btnRed = new javax.swing.JButton();
        btnGreen = new javax.swing.JButton();
        btnBlue = new javax.swing.JButton();
        btnOrange = new javax.swing.JButton();
        btnPurple = new javax.swing.JButton();
        fila0 = new javax.swing.JPanel();
        b00 = new javax.swing.JButton();
        b01 = new javax.swing.JButton();
        b02 = new javax.swing.JButton();
        b03 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        r00 = new javax.swing.JLabel();
        r01 = new javax.swing.JLabel();
        r02 = new javax.swing.JLabel();
        r03 = new javax.swing.JLabel();
        fila1 = new javax.swing.JPanel();
        b12 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        resp1 = new javax.swing.JPanel();
        r10 = new javax.swing.JLabel();
        r11 = new javax.swing.JLabel();
        r12 = new javax.swing.JLabel();
        r13 = new javax.swing.JLabel();
        fila2 = new javax.swing.JPanel();
        b20 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        b23 = new javax.swing.JButton();
        resp2 = new javax.swing.JPanel();
        r20 = new javax.swing.JLabel();
        r21 = new javax.swing.JLabel();
        r22 = new javax.swing.JLabel();
        r23 = new javax.swing.JLabel();
        fila3 = new javax.swing.JPanel();
        b30 = new javax.swing.JButton();
        b31 = new javax.swing.JButton();
        b32 = new javax.swing.JButton();
        b33 = new javax.swing.JButton();
        resp3 = new javax.swing.JPanel();
        r30 = new javax.swing.JLabel();
        r31 = new javax.swing.JLabel();
        r32 = new javax.swing.JLabel();
        r33 = new javax.swing.JLabel();
        fila4 = new javax.swing.JPanel();
        b40 = new javax.swing.JButton();
        b41 = new javax.swing.JButton();
        b42 = new javax.swing.JButton();
        b43 = new javax.swing.JButton();
        resp4 = new javax.swing.JPanel();
        r40 = new javax.swing.JLabel();
        r41 = new javax.swing.JLabel();
        r42 = new javax.swing.JLabel();
        r43 = new javax.swing.JLabel();
        fila5 = new javax.swing.JPanel();
        b50 = new javax.swing.JButton();
        b51 = new javax.swing.JButton();
        b52 = new javax.swing.JButton();
        b53 = new javax.swing.JButton();
        resp5 = new javax.swing.JPanel();
        r50 = new javax.swing.JLabel();
        r51 = new javax.swing.JLabel();
        r52 = new javax.swing.JLabel();
        r53 = new javax.swing.JLabel();
        fila6 = new javax.swing.JPanel();
        b60 = new javax.swing.JButton();
        b61 = new javax.swing.JButton();
        b62 = new javax.swing.JButton();
        b63 = new javax.swing.JButton();
        resp6 = new javax.swing.JPanel();
        r60 = new javax.swing.JLabel();
        r61 = new javax.swing.JLabel();
        r62 = new javax.swing.JLabel();
        r63 = new javax.swing.JLabel();
        fila7 = new javax.swing.JPanel();
        b73 = new javax.swing.JButton();
        b72 = new javax.swing.JButton();
        resp7 = new javax.swing.JPanel();
        r70 = new javax.swing.JLabel();
        r71 = new javax.swing.JLabel();
        r72 = new javax.swing.JLabel();
        r73 = new javax.swing.JLabel();
        b70 = new javax.swing.JButton();
        b71 = new javax.swing.JButton();
        fila8 = new javax.swing.JPanel();
        b80 = new javax.swing.JButton();
        b81 = new javax.swing.JButton();
        b82 = new javax.swing.JButton();
        b83 = new javax.swing.JButton();
        resp8 = new javax.swing.JPanel();
        r80 = new javax.swing.JLabel();
        r81 = new javax.swing.JLabel();
        r82 = new javax.swing.JLabel();
        r83 = new javax.swing.JLabel();
        btnCheck = new javax.swing.JButton();
        txtColores = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnCodeMaker = new javax.swing.JButton();
        solucio = new javax.swing.JPanel();
        sol0 = new javax.swing.JButton();
        sol1 = new javax.swing.JButton();
        sol2 = new javax.swing.JButton();
        sol3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));

        Controles.setBackground(new java.awt.Color(177, 177, 177));
        Controles.setAlignmentX(0.0F);
        Controles.setAlignmentY(0.0F);

        btnRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/red.png"))); // NOI18N
        btnRed.setBorderPainted(false);
        btnRed.setContentAreaFilled(false);
        btnRed.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedActionPerformed(evt);
            }
        });

        btnGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green.png"))); // NOI18N
        btnGreen.setBorderPainted(false);
        btnGreen.setContentAreaFilled(false);
        btnGreen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGreenActionPerformed(evt);
            }
        });

        btnBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue.png"))); // NOI18N
        btnBlue.setBorderPainted(false);
        btnBlue.setContentAreaFilled(false);
        btnBlue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlueActionPerformed(evt);
            }
        });

        btnOrange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/orange.png"))); // NOI18N
        btnOrange.setBorderPainted(false);
        btnOrange.setContentAreaFilled(false);
        btnOrange.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrangeActionPerformed(evt);
            }
        });

        btnPurple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/purple.png"))); // NOI18N
        btnPurple.setBorderPainted(false);
        btnPurple.setContentAreaFilled(false);
        btnPurple.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPurple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurpleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlesLayout = new javax.swing.GroupLayout(Controles);
        Controles.setLayout(ControlesLayout);
        ControlesLayout.setHorizontalGroup(
            ControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ControlesLayout.createSequentialGroup()
                .addComponent(btnRed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGreen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBlue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPurple, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        ControlesLayout.setVerticalGroup(
            ControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnGreen, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnBlue, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnOrange, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnRed))
                    .addComponent(btnPurple, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        b00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b00.setBorderPainted(false);
        b00.setContentAreaFilled(false);
        b00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b00ActionPerformed(evt);
            }
        });

        b01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b01.setBorderPainted(false);
        b01.setContentAreaFilled(false);
        b01.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b01ActionPerformed(evt);
            }
        });

        b02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b02.setBorderPainted(false);
        b02.setContentAreaFilled(false);
        b02.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b02ActionPerformed(evt);
            }
        });

        b03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b03.setBorderPainted(false);
        b03.setContentAreaFilled(false);
        b03.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b03ActionPerformed(evt);
            }
        });

        r00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(r00)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r02))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(r01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r03))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r00)
                    .addComponent(r02))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r01)
                    .addComponent(r03))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fila0Layout = new javax.swing.GroupLayout(fila0);
        fila0.setLayout(fila0Layout);
        fila0Layout.setHorizontalGroup(
            fila0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fila0Layout.createSequentialGroup()
                .addComponent(b00)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b02)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b03)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        fila0Layout.setVerticalGroup(
            fila0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fila0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(b00)
                .addComponent(b01)
                .addComponent(b02)
                .addComponent(b03))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b12.setBorderPainted(false);
        b12.setContentAreaFilled(false);
        b12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });

        b10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b10.setBorderPainted(false);
        b10.setContentAreaFilled(false);
        b10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });

        b11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b11.setBorderPainted(false);
        b11.setContentAreaFilled(false);
        b11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });

        b13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b13.setBorderPainted(false);
        b13.setContentAreaFilled(false);
        b13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });

        r10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        javax.swing.GroupLayout resp1Layout = new javax.swing.GroupLayout(resp1);
        resp1.setLayout(resp1Layout);
        resp1Layout.setHorizontalGroup(
            resp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resp1Layout.createSequentialGroup()
                .addComponent(r10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r12))
            .addGroup(resp1Layout.createSequentialGroup()
                .addComponent(r11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r13))
        );
        resp1Layout.setVerticalGroup(
            resp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resp1Layout.createSequentialGroup()
                .addGroup(resp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r10)
                    .addComponent(r12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(resp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r11)
                    .addComponent(r13))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fila1Layout = new javax.swing.GroupLayout(fila1);
        fila1.setLayout(fila1Layout);
        fila1Layout.setHorizontalGroup(
            fila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fila1Layout.createSequentialGroup()
                .addComponent(b10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        fila1Layout.setVerticalGroup(
            fila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fila1Layout.createSequentialGroup()
                .addGroup(fila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b10)
                        .addComponent(b11)
                        .addComponent(b13))
                    .addComponent(b12))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        b20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b20.setBorderPainted(false);
        b20.setContentAreaFilled(false);
        b20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b20ActionPerformed(evt);
            }
        });

        b21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b21.setBorderPainted(false);
        b21.setContentAreaFilled(false);
        b21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b21ActionPerformed(evt);
            }
        });

        b22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b22.setBorderPainted(false);
        b22.setContentAreaFilled(false);
        b22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b22ActionPerformed(evt);
            }
        });

        b23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b23.setBorderPainted(false);
        b23.setContentAreaFilled(false);
        b23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b23ActionPerformed(evt);
            }
        });

        r20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        javax.swing.GroupLayout resp2Layout = new javax.swing.GroupLayout(resp2);
        resp2.setLayout(resp2Layout);
        resp2Layout.setHorizontalGroup(
            resp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resp2Layout.createSequentialGroup()
                .addComponent(r20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r22))
            .addGroup(resp2Layout.createSequentialGroup()
                .addComponent(r21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r23))
        );
        resp2Layout.setVerticalGroup(
            resp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resp2Layout.createSequentialGroup()
                .addGroup(resp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r20)
                    .addComponent(r22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(resp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r21)
                    .addComponent(r23)))
        );

        javax.swing.GroupLayout fila2Layout = new javax.swing.GroupLayout(fila2);
        fila2.setLayout(fila2Layout);
        fila2Layout.setHorizontalGroup(
            fila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fila2Layout.createSequentialGroup()
                .addComponent(b20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fila2Layout.setVerticalGroup(
            fila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(b20)
                .addComponent(b21)
                .addComponent(b22)
                .addComponent(b23))
            .addComponent(resp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        b30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b30.setBorderPainted(false);
        b30.setContentAreaFilled(false);
        b30.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b30ActionPerformed(evt);
            }
        });

        b31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b31.setBorderPainted(false);
        b31.setContentAreaFilled(false);
        b31.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b31ActionPerformed(evt);
            }
        });

        b32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b32.setBorderPainted(false);
        b32.setContentAreaFilled(false);
        b32.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b32ActionPerformed(evt);
            }
        });

        b33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b33.setBorderPainted(false);
        b33.setContentAreaFilled(false);
        b33.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b33ActionPerformed(evt);
            }
        });

        r30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        javax.swing.GroupLayout resp3Layout = new javax.swing.GroupLayout(resp3);
        resp3.setLayout(resp3Layout);
        resp3Layout.setHorizontalGroup(
            resp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resp3Layout.createSequentialGroup()
                .addComponent(r30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r32))
            .addGroup(resp3Layout.createSequentialGroup()
                .addComponent(r31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r33))
        );
        resp3Layout.setVerticalGroup(
            resp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resp3Layout.createSequentialGroup()
                .addGroup(resp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r30)
                    .addComponent(r32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(resp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r31)
                    .addComponent(r33)))
        );

        javax.swing.GroupLayout fila3Layout = new javax.swing.GroupLayout(fila3);
        fila3.setLayout(fila3Layout);
        fila3Layout.setHorizontalGroup(
            fila3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fila3Layout.createSequentialGroup()
                .addComponent(b30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        fila3Layout.setVerticalGroup(
            fila3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resp3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fila3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(b30)
                .addComponent(b31)
                .addComponent(b32)
                .addComponent(b33))
        );

        b40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b40.setBorderPainted(false);
        b40.setContentAreaFilled(false);
        b40.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b40ActionPerformed(evt);
            }
        });

        b41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b41.setBorderPainted(false);
        b41.setContentAreaFilled(false);
        b41.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b41ActionPerformed(evt);
            }
        });

        b42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b42.setBorderPainted(false);
        b42.setContentAreaFilled(false);
        b42.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b42ActionPerformed(evt);
            }
        });

        b43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b43.setBorderPainted(false);
        b43.setContentAreaFilled(false);
        b43.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b43ActionPerformed(evt);
            }
        });

        r40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        javax.swing.GroupLayout resp4Layout = new javax.swing.GroupLayout(resp4);
        resp4.setLayout(resp4Layout);
        resp4Layout.setHorizontalGroup(
            resp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resp4Layout.createSequentialGroup()
                .addComponent(r40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r42))
            .addGroup(resp4Layout.createSequentialGroup()
                .addComponent(r41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r43))
        );
        resp4Layout.setVerticalGroup(
            resp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resp4Layout.createSequentialGroup()
                .addGroup(resp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r40)
                    .addComponent(r42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(resp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r41)
                    .addComponent(r43)))
        );

        javax.swing.GroupLayout fila4Layout = new javax.swing.GroupLayout(fila4);
        fila4.setLayout(fila4Layout);
        fila4Layout.setHorizontalGroup(
            fila4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fila4Layout.createSequentialGroup()
                .addComponent(b40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        fila4Layout.setVerticalGroup(
            fila4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(fila4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(b40)
                .addComponent(b41)
                .addComponent(b42)
                .addComponent(b43))
            .addComponent(resp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        b50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b50.setBorderPainted(false);
        b50.setContentAreaFilled(false);
        b50.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b50ActionPerformed(evt);
            }
        });

        b51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b51.setBorderPainted(false);
        b51.setContentAreaFilled(false);
        b51.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b51ActionPerformed(evt);
            }
        });

        b52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b52.setBorderPainted(false);
        b52.setContentAreaFilled(false);
        b52.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b52ActionPerformed(evt);
            }
        });

        b53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b53.setBorderPainted(false);
        b53.setContentAreaFilled(false);
        b53.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b53ActionPerformed(evt);
            }
        });

        r50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        javax.swing.GroupLayout resp5Layout = new javax.swing.GroupLayout(resp5);
        resp5.setLayout(resp5Layout);
        resp5Layout.setHorizontalGroup(
            resp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resp5Layout.createSequentialGroup()
                .addComponent(r50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r52))
            .addGroup(resp5Layout.createSequentialGroup()
                .addComponent(r51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r53))
        );
        resp5Layout.setVerticalGroup(
            resp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resp5Layout.createSequentialGroup()
                .addGroup(resp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r50)
                    .addComponent(r52))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(resp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r51)
                    .addComponent(r53)))
        );

        javax.swing.GroupLayout fila5Layout = new javax.swing.GroupLayout(fila5);
        fila5.setLayout(fila5Layout);
        fila5Layout.setHorizontalGroup(
            fila5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fila5Layout.createSequentialGroup()
                .addComponent(b50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        fila5Layout.setVerticalGroup(
            fila5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fila5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(b50)
                .addComponent(b51)
                .addComponent(b52)
                .addComponent(b53))
            .addComponent(resp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        b60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b60.setBorderPainted(false);
        b60.setContentAreaFilled(false);
        b60.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b60ActionPerformed(evt);
            }
        });

        b61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b61.setBorderPainted(false);
        b61.setContentAreaFilled(false);
        b61.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b61ActionPerformed(evt);
            }
        });

        b62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b62.setBorderPainted(false);
        b62.setContentAreaFilled(false);
        b62.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b62ActionPerformed(evt);
            }
        });

        b63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b63.setBorderPainted(false);
        b63.setContentAreaFilled(false);
        b63.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b63ActionPerformed(evt);
            }
        });

        r60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        javax.swing.GroupLayout resp6Layout = new javax.swing.GroupLayout(resp6);
        resp6.setLayout(resp6Layout);
        resp6Layout.setHorizontalGroup(
            resp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resp6Layout.createSequentialGroup()
                .addComponent(r60)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r62))
            .addGroup(resp6Layout.createSequentialGroup()
                .addComponent(r61)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r63))
        );
        resp6Layout.setVerticalGroup(
            resp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resp6Layout.createSequentialGroup()
                .addGroup(resp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r60)
                    .addComponent(r62))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(resp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r61)
                    .addComponent(r63)))
        );

        javax.swing.GroupLayout fila6Layout = new javax.swing.GroupLayout(fila6);
        fila6.setLayout(fila6Layout);
        fila6Layout.setHorizontalGroup(
            fila6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fila6Layout.createSequentialGroup()
                .addComponent(b60)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b61)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b62)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b63)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        fila6Layout.setVerticalGroup(
            fila6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fila6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(b60)
                .addComponent(b61)
                .addComponent(b62)
                .addComponent(b63))
            .addComponent(resp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        b73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b73.setBorderPainted(false);
        b73.setContentAreaFilled(false);
        b73.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b73ActionPerformed(evt);
            }
        });

        b72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b72.setBorderPainted(false);
        b72.setContentAreaFilled(false);
        b72.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b72ActionPerformed(evt);
            }
        });

        r70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        javax.swing.GroupLayout resp7Layout = new javax.swing.GroupLayout(resp7);
        resp7.setLayout(resp7Layout);
        resp7Layout.setHorizontalGroup(
            resp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resp7Layout.createSequentialGroup()
                .addComponent(r70)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r72))
            .addGroup(resp7Layout.createSequentialGroup()
                .addComponent(r71)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r73))
        );
        resp7Layout.setVerticalGroup(
            resp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resp7Layout.createSequentialGroup()
                .addGroup(resp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r70)
                    .addComponent(r72))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(resp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r71)
                    .addComponent(r73)))
        );

        b70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b70.setBorderPainted(false);
        b70.setContentAreaFilled(false);
        b70.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b70ActionPerformed(evt);
            }
        });

        b71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b71.setBorderPainted(false);
        b71.setContentAreaFilled(false);
        b71.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b71ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fila7Layout = new javax.swing.GroupLayout(fila7);
        fila7.setLayout(fila7Layout);
        fila7Layout.setHorizontalGroup(
            fila7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fila7Layout.createSequentialGroup()
                .addComponent(b70)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b71)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b72)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b73)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resp7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        fila7Layout.setVerticalGroup(
            fila7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(b73)
            .addComponent(b72)
            .addComponent(resp7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(b70)
            .addComponent(b71)
        );

        b80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b80.setBorderPainted(false);
        b80.setContentAreaFilled(false);
        b80.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b80ActionPerformed(evt);
            }
        });

        b81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b81.setBorderPainted(false);
        b81.setContentAreaFilled(false);
        b81.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b81ActionPerformed(evt);
            }
        });

        b82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b82.setBorderPainted(false);
        b82.setContentAreaFilled(false);
        b82.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b82ActionPerformed(evt);
            }
        });

        b83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        b83.setBorderPainted(false);
        b83.setContentAreaFilled(false);
        b83.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b83ActionPerformed(evt);
            }
        });

        r80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        r83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/espigaVacia.png"))); // NOI18N

        javax.swing.GroupLayout resp8Layout = new javax.swing.GroupLayout(resp8);
        resp8.setLayout(resp8Layout);
        resp8Layout.setHorizontalGroup(
            resp8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resp8Layout.createSequentialGroup()
                .addComponent(r80)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r82))
            .addGroup(resp8Layout.createSequentialGroup()
                .addComponent(r81)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r83))
        );
        resp8Layout.setVerticalGroup(
            resp8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resp8Layout.createSequentialGroup()
                .addGroup(resp8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r80)
                    .addComponent(r82))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(resp8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r81)
                    .addComponent(r83)))
        );

        javax.swing.GroupLayout fila8Layout = new javax.swing.GroupLayout(fila8);
        fila8.setLayout(fila8Layout);
        fila8Layout.setHorizontalGroup(
            fila8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fila8Layout.createSequentialGroup()
                .addComponent(b80)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b81)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b82)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b83)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resp8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        fila8Layout.setVerticalGroup(
            fila8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fila8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(b80)
                .addComponent(b81)
                .addComponent(b82)
                .addComponent(b83))
            .addComponent(resp8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnCheck.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnCheck.setForeground(new java.awt.Color(4, 147, 18));
        btnCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check.png"))); // NOI18N
        btnCheck.setText("Check");
        btnCheck.setIconTextGap(30);
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        txtColores.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtColores.setText("Colores disponibles");

        btnGuardar.setText("Guardar partida");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnMenu.setText("Sortir");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnCodeMaker.setText("Jugar com CodeMaker (test only)");
        btnCodeMaker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodeMakerActionPerformed(evt);
            }
        });

        solucio.setBackground(new java.awt.Color(184, 254, 107));

        sol0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        sol0.setBorderPainted(false);
        sol0.setContentAreaFilled(false);
        sol0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        sol1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        sol1.setBorderPainted(false);
        sol1.setContentAreaFilled(false);
        sol1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        sol2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        sol2.setBorderPainted(false);
        sol2.setContentAreaFilled(false);
        sol2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        sol3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empty.png"))); // NOI18N
        sol3.setBorderPainted(false);
        sol3.setContentAreaFilled(false);
        sol3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout solucioLayout = new javax.swing.GroupLayout(solucio);
        solucio.setLayout(solucioLayout);
        solucioLayout.setHorizontalGroup(
            solucioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solucioLayout.createSequentialGroup()
                .addComponent(sol0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sol1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sol2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sol3))
        );
        solucioLayout.setVerticalGroup(
            solucioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solucioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(sol0)
                .addComponent(sol1)
                .addComponent(sol2)
                .addComponent(sol3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fila5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fila7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(fila8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fila6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(solucio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(139, 139, 139)
                .addComponent(btnCodeMaker)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fila3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(118, 118, 118))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fila4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Controles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txtColores))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fila2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(fila0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fila1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fila0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fila1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fila2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fila3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fila4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fila5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fila6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fila7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtColores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Controles, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCheck)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fila8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(solucio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCodeMaker)
                        .addGap(41, 41, 41))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
       editable++;
       p.controller.ferJugada(codi);
       codi[0] = 0;
       codi[1] = 0;
       codi[2] = 0;
       codi[3] = 0;
    }//GEN-LAST:event_btnCheckActionPerformed

    private void b20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b20ActionPerformed
        clickHecho(b20, 2, 0);
    }//GEN-LAST:event_b20ActionPerformed

    private void b21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b21ActionPerformed
        clickHecho(b21, 2, 1);
    }//GEN-LAST:event_b21ActionPerformed

    private void b22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b22ActionPerformed
        clickHecho(b22, 2, 2);
    }//GEN-LAST:event_b22ActionPerformed

    private void b23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b23ActionPerformed
        clickHecho(b23, 2, 3);
    }//GEN-LAST:event_b23ActionPerformed

    private void b30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b30ActionPerformed
        clickHecho(b30, 3, 0);
    }//GEN-LAST:event_b30ActionPerformed

    private void b31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b31ActionPerformed
        clickHecho(b31, 3, 1);
    }//GEN-LAST:event_b31ActionPerformed

    private void b32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b32ActionPerformed
        clickHecho(b32, 3, 2);
    }//GEN-LAST:event_b32ActionPerformed

    private void b33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b33ActionPerformed
        clickHecho(b33, 3, 3);
    }//GEN-LAST:event_b33ActionPerformed

    private void b40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b40ActionPerformed
        clickHecho(b40, 4, 0);
    }//GEN-LAST:event_b40ActionPerformed

    private void b41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b41ActionPerformed
        clickHecho(b41, 4, 1);
    }//GEN-LAST:event_b41ActionPerformed

    private void b42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b42ActionPerformed
        clickHecho(b42, 4, 2);
    }//GEN-LAST:event_b42ActionPerformed

    private void b43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b43ActionPerformed
        clickHecho(b43, 4, 3);
    }//GEN-LAST:event_b43ActionPerformed

    private void b50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b50ActionPerformed
        clickHecho(b50, 5, 0);
    }//GEN-LAST:event_b50ActionPerformed

    private void b51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b51ActionPerformed
        clickHecho(b51, 5, 1);
    }//GEN-LAST:event_b51ActionPerformed

    private void b52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b52ActionPerformed
        clickHecho(b52, 5, 2);
    }//GEN-LAST:event_b52ActionPerformed

    private void b53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b53ActionPerformed
        clickHecho(b53, 5, 3);
    }//GEN-LAST:event_b53ActionPerformed

    private void b60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b60ActionPerformed
        clickHecho(b60, 6, 0);
    }//GEN-LAST:event_b60ActionPerformed

    private void b61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b61ActionPerformed
        clickHecho(b61, 6, 1);
    }//GEN-LAST:event_b61ActionPerformed

    private void b62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b62ActionPerformed
        clickHecho(b62, 6, 2);
    }//GEN-LAST:event_b62ActionPerformed

    private void b63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b63ActionPerformed
        clickHecho(b63, 6, 3);
    }//GEN-LAST:event_b63ActionPerformed

    private void b70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b70ActionPerformed
        clickHecho(b70, 7, 0);
    }//GEN-LAST:event_b70ActionPerformed

    private void b71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b71ActionPerformed
        clickHecho(b71, 7, 1);
    }//GEN-LAST:event_b71ActionPerformed

    private void b72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b72ActionPerformed
        clickHecho(b72, 7, 2);
    }//GEN-LAST:event_b72ActionPerformed

    private void b73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b73ActionPerformed
        clickHecho(b73, 7, 3);
    }//GEN-LAST:event_b73ActionPerformed

    private void b80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b80ActionPerformed
        clickHecho(b80, 8, 0);
    }//GEN-LAST:event_b80ActionPerformed

    private void b81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b81ActionPerformed
        clickHecho(b81, 8, 1);
    }//GEN-LAST:event_b81ActionPerformed

    private void b82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b82ActionPerformed
        clickHecho(b82, 8, 2);
    }//GEN-LAST:event_b82ActionPerformed

    private void b83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b83ActionPerformed
        clickHecho(b83, 8, 3);
    }//GEN-LAST:event_b83ActionPerformed

    private void b03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b03ActionPerformed
        clickHecho(b03, 0, 3);
    }//GEN-LAST:event_b03ActionPerformed

    private void b02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b02ActionPerformed
        clickHecho(b02, 0, 2);
    }//GEN-LAST:event_b02ActionPerformed

    private void b01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b01ActionPerformed
        clickHecho(b01, 0, 1);
    }//GEN-LAST:event_b01ActionPerformed

    private void b00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b00ActionPerformed
        clickHecho(b00, 0, 0);
    }//GEN-LAST:event_b00ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
        clickHecho(b13, 1, 3);
    }//GEN-LAST:event_b13ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        clickHecho(b12, 1, 2);
    }//GEN-LAST:event_b12ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        clickHecho(b11, 1, 1);
    }//GEN-LAST:event_b11ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        clickHecho(b10, 1, 0);
    }//GEN-LAST:event_b10ActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        MenuPrincipal nova = new MenuPrincipal();
        nova.setVisible(true);
        Partida.this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        p.controller.guardarPartida();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnPurpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurpleActionPerformed
        selectedColor = "/images/purple.png";
        selectedInt = 4;
    }//GEN-LAST:event_btnPurpleActionPerformed

    private void btnOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrangeActionPerformed
        selectedColor = "/images/orange.png";
        selectedInt = 3;
    }//GEN-LAST:event_btnOrangeActionPerformed

    private void btnBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlueActionPerformed
        selectedColor = "/images/blue.png";
        selectedInt = 2;
    }//GEN-LAST:event_btnBlueActionPerformed

    private void btnGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGreenActionPerformed
        selectedColor = "/images/green.png";
        selectedInt = 1;
    }//GEN-LAST:event_btnGreenActionPerformed

    private void btnRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedActionPerformed
        selectedColor = "/images/red.png";
        selectedInt = 0;
    }//GEN-LAST:event_btnRedActionPerformed

    private void btnCodeMakerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodeMakerActionPerformed
        if (p.controller.esCodeMaker()) {
            p.controller.jugaCodeMaker();
        }
    }//GEN-LAST:event_btnCodeMakerActionPerformed

    private void clickHecho(JButton btn, int fila, int pos) {
        if (editable == fila) {
            btn.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedColor)));
            codi[pos] = selectedInt;
        }
    }
    
    private boolean haGuanyat(ArrayList<String> codiR) {
        return (codiR.get(0) == "/images/espigaNegra.png" && codiR.get(1) == "/images/espigaNegra.png" &&
                codiR.get(2) == "/images/espigaNegra.png" && codiR.get(3) == "/images/espigaNegra.png");
    }
    
    public void mostraCodiRespost(ArrayList<String> codiR, int numJugada) {
        int i = 0;
        for (JLabel r : respostes.get(numJugada)) {
            r.setIcon(new javax.swing.ImageIcon(getClass().getResource(codiR.get(i))));
            ++i;
        }
        // Si perd
        if (p.controller.haPerdut()) {
            JOptionPane.showMessageDialog(null, "Has perdut!");
            p.controller.acabaPartida();
        }
        // Si guanya
        else if (p.controller.haGuanyat()) {
            JOptionPane.showMessageDialog(null, "Has guanyat!");
            editable = 500;
            ArrayList<String> sols = p.controller.getSolucio();
            sol0.setIcon(new javax.swing.ImageIcon(getClass().getResource(sols.get(0))));
            sol1.setIcon(new javax.swing.ImageIcon(getClass().getResource(sols.get(1))));
            sol2.setIcon(new javax.swing.ImageIcon(getClass().getResource(sols.get(2))));
            sol3.setIcon(new javax.swing.ImageIcon(getClass().getResource(sols.get(3))));
            p.controller.acabaPartida();
        }
    }
    
    public void pintaJugada(ArrayList<String> codiR, int numJugada) {
        int i = 0;
        for (JButton b : combinacions.get(numJugada)) {
            b.setIcon(new javax.swing.ImageIcon(getClass().getResource(codiR.get(i))));
            ++i;
        }
    }
    
    private void ferGrupsRespostes() {
        respostes = new ArrayList<ArrayList<JLabel>>();
        
        res0 = new ArrayList<JLabel>();
        res0.add(r00);
        res0.add(r01);
        res0.add(r02);
        res0.add(r03);
        respostes.add(res0);
        
        res1 = new ArrayList<JLabel>();
        res1.add(r10);
        res1.add(r11);
        res1.add(r12);
        res1.add(r13);
        respostes.add(res1);
        
        res2 = new ArrayList<JLabel>();
        res2.add(r20);
        res2.add(r21);
        res2.add(r22);
        res2.add(r23);
        respostes.add(res2);
        
        res3 = new ArrayList<JLabel>();
        res3.add(r30);
        res3.add(r31);
        res3.add(r32);
        res3.add(r33);
        respostes.add(res3);
        
        res4 = new ArrayList<JLabel>();
        res4.add(r40);
        res4.add(r41);
        res4.add(r42);
        res4.add(r43);
        respostes.add(res4);
        
        res5 = new ArrayList<JLabel>();
        res5.add(r50);
        res5.add(r51);
        res5.add(r52);
        res5.add(r53);
        respostes.add(res5);
        
        res6 = new ArrayList<JLabel>();
        res6.add(r60);
        res6.add(r61);
        res6.add(r62);
        res6.add(r63);
        respostes.add(res6);
        
        res7 = new ArrayList<JLabel>();
        res7.add(r70);
        res7.add(r71);
        res7.add(r72);
        res7.add(r73);
        respostes.add(res7);
        
        res8 = new ArrayList<JLabel>();
        res8.add(r80);
        res8.add(r81);
        res8.add(r82);
        res8.add(r83);
        respostes.add(res8);
    }
    
    private void ferGrupsCombinacions() {
        combinacions = new ArrayList<ArrayList<JButton>>();
        
        comb0 = new ArrayList<JButton>();
        comb0.add(b00);
        comb0.add(b01);
        comb0.add(b02);
        comb0.add(b03);
        combinacions.add(comb0);
        
        comb1 = new ArrayList<JButton>();
        comb1.add(b10);
        comb1.add(b11);
        comb1.add(b12);
        comb1.add(b13);
        combinacions.add(comb1);
        
        comb2 = new ArrayList<JButton>();
        comb2.add(b20);
        comb2.add(b21);
        comb2.add(b22);
        comb2.add(b23);
        combinacions.add(comb2);
        
        comb3 = new ArrayList<JButton>();
        comb3.add(b30);
        comb3.add(b31);
        comb3.add(b32);
        comb3.add(b33);
        combinacions.add(comb3);
        
        comb4 = new ArrayList<JButton>();
        comb4.add(b40);
        comb4.add(b41);
        comb4.add(b42);
        comb4.add(b43);
        combinacions.add(comb4);
        
        comb5 = new ArrayList<JButton>();
        comb5.add(b50);
        comb5.add(b51);
        comb5.add(b52);
        comb5.add(b53);
        combinacions.add(comb5);
        
        comb6 = new ArrayList<JButton>();
        comb6.add(b60);
        comb6.add(b61);
        comb6.add(b62);
        comb6.add(b63);
        combinacions.add(comb6);
        
        comb7 = new ArrayList<JButton>();
        comb7.add(b70);
        comb7.add(b71);
        comb7.add(b72);
        comb7.add(b73);
        combinacions.add(comb7);
        
        comb8 = new ArrayList<JButton>();
        comb8.add(b80);
        comb8.add(b81);
        comb8.add(b82);
        comb8.add(b83);
        combinacions.add(comb8);
    }
    
    public void setEditable(int e) {
        editable = e;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Partida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Controles;
    private javax.swing.JButton b00;
    private javax.swing.JButton b01;
    private javax.swing.JButton b02;
    private javax.swing.JButton b03;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b20;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JButton b23;
    private javax.swing.JButton b30;
    private javax.swing.JButton b31;
    private javax.swing.JButton b32;
    private javax.swing.JButton b33;
    private javax.swing.JButton b40;
    private javax.swing.JButton b41;
    private javax.swing.JButton b42;
    private javax.swing.JButton b43;
    private javax.swing.JButton b50;
    private javax.swing.JButton b51;
    private javax.swing.JButton b52;
    private javax.swing.JButton b53;
    private javax.swing.JButton b60;
    private javax.swing.JButton b61;
    private javax.swing.JButton b62;
    private javax.swing.JButton b63;
    private javax.swing.JButton b70;
    private javax.swing.JButton b71;
    private javax.swing.JButton b72;
    private javax.swing.JButton b73;
    private javax.swing.JButton b80;
    private javax.swing.JButton b81;
    private javax.swing.JButton b82;
    private javax.swing.JButton b83;
    private javax.swing.JButton btnBlue;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnCodeMaker;
    private javax.swing.JButton btnGreen;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnOrange;
    private javax.swing.JButton btnPurple;
    private javax.swing.JButton btnRed;
    private javax.swing.JPanel fila0;
    private javax.swing.JPanel fila1;
    private javax.swing.JPanel fila2;
    private javax.swing.JPanel fila3;
    private javax.swing.JPanel fila4;
    private javax.swing.JPanel fila5;
    private javax.swing.JPanel fila6;
    private javax.swing.JPanel fila7;
    private javax.swing.JPanel fila8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel r00;
    private javax.swing.JLabel r01;
    private javax.swing.JLabel r02;
    private javax.swing.JLabel r03;
    private javax.swing.JLabel r10;
    private javax.swing.JLabel r11;
    private javax.swing.JLabel r12;
    private javax.swing.JLabel r13;
    private javax.swing.JLabel r20;
    private javax.swing.JLabel r21;
    private javax.swing.JLabel r22;
    private javax.swing.JLabel r23;
    private javax.swing.JLabel r30;
    private javax.swing.JLabel r31;
    private javax.swing.JLabel r32;
    private javax.swing.JLabel r33;
    private javax.swing.JLabel r40;
    private javax.swing.JLabel r41;
    private javax.swing.JLabel r42;
    private javax.swing.JLabel r43;
    private javax.swing.JLabel r50;
    private javax.swing.JLabel r51;
    private javax.swing.JLabel r52;
    private javax.swing.JLabel r53;
    private javax.swing.JLabel r60;
    private javax.swing.JLabel r61;
    private javax.swing.JLabel r62;
    private javax.swing.JLabel r63;
    private javax.swing.JLabel r70;
    private javax.swing.JLabel r71;
    private javax.swing.JLabel r72;
    private javax.swing.JLabel r73;
    private javax.swing.JLabel r80;
    private javax.swing.JLabel r81;
    private javax.swing.JLabel r82;
    private javax.swing.JLabel r83;
    private javax.swing.JPanel resp1;
    private javax.swing.JPanel resp2;
    private javax.swing.JPanel resp3;
    private javax.swing.JPanel resp4;
    private javax.swing.JPanel resp5;
    private javax.swing.JPanel resp6;
    private javax.swing.JPanel resp7;
    private javax.swing.JPanel resp8;
    private javax.swing.JButton sol0;
    private javax.swing.JButton sol1;
    private javax.swing.JButton sol2;
    private javax.swing.JButton sol3;
    private javax.swing.JPanel solucio;
    private javax.swing.JLabel txtColores;
    // End of variables declaration//GEN-END:variables

}
