package com.prop.presentacio;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;

public class VistaPartida {
    private JButton checkButton;
    private JButton btnRed;
    private JButton btnGreen;
    private JButton btnBlue;
    private JButton btnOrange;
    private JPanel selectorPanel;
    private JPanel toolsPanel;
    private JPanel playerPanel;
    private JPanel fila0;
    private JPanel panelMain;
    private JButton b00;
    private JButton b01;
    private JButton b02;
    private JButton b03;
    private JButton b122;
    private JButton b11;
    private JPanel fila1;
    private JButton b12;
    private JButton b13;
    private JButton b23;
    private JButton b22;
    private JButton b20;
    private JButton b21;
    private JPanel fila2;
    private JButton b10;
    private JButton b32;
    private JPanel fila3;
    private JButton b33;
    private JButton b30;
    private JButton b31;
    private JPanel fila4;
    private JButton b40;
    private JButton b43;
    private JButton b41;
    private JButton b42;
    private JButton b51;
    private JButton b52;
    private JButton b53;
    private JButton b50;
    private JPanel fila5;
    private JButton b63;
    private JPanel fila6;
    private JButton b61;
    private JButton b60;
    private JButton b62;

    private ArrayList<JButton> btns = new ArrayList<JButton>();
    private int editable = 0;
    private Color colorSelected;
    private int filaActual;
    private int botoActual;

    public static void main(String[] args) {
        JFrame frame = new JFrame("VistaPartida");
        frame.setContentPane(new VistaPartida().panelMain);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public VistaPartida() {
        $$$setupUI$$$();
        btns.add(b00);
        btns.add(b01);
        btns.add(b02);
        btns.add(b03);
        btns.add(b10);
        btns.add(b11);
        btns.add(b12);
        btns.add(b13);
        btns.add(b20);
        btns.add(b21);
        btns.add(b22);
        btns.add(b23);
        btns.add(b30);
        btns.add(b31);
        btns.add(b32);
        btns.add(b33);
        btns.add(b40);
        btns.add(b41);
        btns.add(b42);
        btns.add(b43);
        btns.add(b50);
        btns.add(b51);
        btns.add(b52);
        btns.add(b53);
        btns.add(b60);
        btns.add(b61);
        btns.add(b62);
        btns.add(b63);

        filaActual = botoActual = 0;
        for (JButton b : btns) {
            botoActual = botoActual + 1;
            if (botoActual == 4) {
                botoActual = 0;
                filaActual = filaActual + 1;
            }
            b.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent mouseEvent) {
                    super.mouseClicked(mouseEvent);
                    b.get
                    if (editable == filaActual) b.setBackground(colorSelected);
                    System.out.println("Fila " + filaActual + ", Botó " + botoActual);
                }
            });
        }

        checkButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                editable++;
            }
        });

        btnRed.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent mouseEvent) {
                super.mouseClicked(mouseEvent);
                colorSelected = Color.RED;
            }
        });
        btnGreen.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent mouseEvent) {
                super.mouseClicked(mouseEvent);
                colorSelected = Color.GREEN;
            }
        });
        btnBlue.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent mouseEvent) {
                super.mouseClicked(mouseEvent);
                colorSelected = Color.BLUE;
            }
        });
        btnOrange.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent mouseEvent) {
                super.mouseClicked(mouseEvent);
                colorSelected = Color.ORANGE;
            }
        });
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        toolsPanel = new JPanel();
        toolsPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 3, new Insets(20, 20, 20, 20), -1, -1));
        panelMain.add(toolsPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        checkButton = new JButton();
        checkButton.setText("Check");
        toolsPanel.add(checkButton, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        selectorPanel = new JPanel();
        selectorPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 4, new Insets(0, 0, 0, 0), -1, -1));
        toolsPanel.add(selectorPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        btnRed = new JButton();
        btnRed.setHorizontalTextPosition(0);
        btnRed.setText("");
        selectorPanel.add(btnRed, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnGreen = new JButton();
        btnGreen.setText("");
        selectorPanel.add(btnGreen, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnBlue = new JButton();
        btnBlue.setText("");
        selectorPanel.add(btnBlue, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnOrange = new JButton();
        btnOrange.setText("");
        selectorPanel.add(btnOrange, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        toolsPanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        panelMain.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        playerPanel = new JPanel();
        playerPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(8, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelMain.add(playerPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        fila0 = new JPanel();
        fila0.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 4, new Insets(20, 20, 0, 20), -1, -1));
        fila0.setEnabled(true);
        playerPanel.add(fila0, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        b00 = new JButton();
        b00.setEnabled(true);
        Font b00Font = this.$$$getFont$$$(null, -1, -1, b00.getFont());
        if (b00Font != null) b00.setFont(b00Font);
        b00.setHideActionText(false);
        b00.setHorizontalTextPosition(0);
        b00.setText("");
        fila0.add(b00, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        b01 = new JButton();
        b01.setEnabled(true);
        Font b01Font = this.$$$getFont$$$(null, -1, -1, b01.getFont());
        if (b01Font != null) b01.setFont(b01Font);
        b01.setHideActionText(false);
        b01.setHorizontalTextPosition(0);
        b01.setText("");
        fila0.add(b01, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        b02 = new JButton();
        b02.setEnabled(true);
        Font b02Font = this.$$$getFont$$$(null, -1, -1, b02.getFont());
        if (b02Font != null) b02.setFont(b02Font);
        b02.setHideActionText(false);
        b02.setHorizontalTextPosition(0);
        b02.setText("");
        fila0.add(b02, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        b03 = new JButton();
        b03.setEnabled(true);
        Font b03Font = this.$$$getFont$$$(null, -1, -1, b03.getFont());
        if (b03Font != null) b03.setFont(b03Font);
        b03.setHideActionText(false);
        b03.setHorizontalTextPosition(0);
        b03.setText("");
        fila0.add(b03, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        fila1 = new JPanel();
        fila1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 4, new Insets(0, 20, 0, 20), -1, -1));
        fila1.setEnabled(true);
        playerPanel.add(fila1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        b10 = new JButton();
        b10.setEnabled(true);
        Font b10Font = this.$$$getFont$$$(null, -1, -1, b10.getFont());
        if (b10Font != null) b10.setFont(b10Font);
        b10.setHideActionText(false);
        b10.setHorizontalTextPosition(0);
        b10.setText("");
        fila1.add(b10, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        b11 = new JButton();
        b11.setEnabled(true);
        Font b11Font = this.$$$getFont$$$(null, -1, -1, b11.getFont());
        if (b11Font != null) b11.setFont(b11Font);
        b11.setHideActionText(false);
        b11.setHorizontalTextPosition(0);
        b11.setText("");
        fila1.add(b11, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        b12 = new JButton();
        b12.setEnabled(true);
        Font b12Font = this.$$$getFont$$$(null, -1, -1, b12.getFont());
        if (b12Font != null) b12.setFont(b12Font);
        b12.setHideActionText(false);
        b12.setHorizontalTextPosition(0);
        b12.setText("");
        fila1.add(b12, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        b13 = new JButton();
        b13.setEnabled(true);
        Font b13Font = this.$$$getFont$$$(null, -1, -1, b13.getFont());
        if (b13Font != null) b13.setFont(b13Font);
        b13.setHideActionText(false);
        b13.setHorizontalTextPosition(0);
        b13.setText("");
        fila1.add(b13, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        fila2 = new JPanel();
        fila2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 4, new Insets(0, 20, 0, 20), -1, -1));
        fila2.setEnabled(true);
        playerPanel.add(fila2, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        b20 = new JButton();
        b20.setEnabled(true);
        Font b20Font = this.$$$getFont$$$(null, -1, -1, b20.getFont());
        if (b20Font != null) b20.setFont(b20Font);
        b20.setHideActionText(false);
        b20.setHorizontalTextPosition(0);
        b20.setText("");
        fila2.add(b20, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        b21 = new JButton();
        b21.setEnabled(true);
        Font b21Font = this.$$$getFont$$$(null, -1, -1, b21.getFont());
        if (b21Font != null) b21.setFont(b21Font);
        b21.setHideActionText(false);
        b21.setHorizontalTextPosition(0);
        b21.setText("");
        fila2.add(b21, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        b22 = new JButton();
        b22.setEnabled(true);
        Font b22Font = this.$$$getFont$$$(null, -1, -1, b22.getFont());
        if (b22Font != null) b22.setFont(b22Font);
        b22.setHideActionText(false);
        b22.setHorizontalTextPosition(0);
        b22.setText("");
        fila2.add(b22, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        b23 = new JButton();
        b23.setEnabled(true);
        Font b23Font = this.$$$getFont$$$(null, -1, -1, b23.getFont());
        if (b23Font != null) b23.setFont(b23Font);
        b23.setHideActionText(false);
        b23.setHorizontalTextPosition(0);
        b23.setText("");
        fila2.add(b23, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        fila3 = new JPanel();
        fila3.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 4, new Insets(0, 20, 0, 20), -1, -1));
        fila3.setEnabled(true);
        playerPanel.add(fila3, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        b30 = new JButton();
        b30.setEnabled(true);
        Font b30Font = this.$$$getFont$$$(null, -1, -1, b30.getFont());
        if (b30Font != null) b30.setFont(b30Font);
        b30.setHideActionText(false);
        b30.setHorizontalTextPosition(0);
        b30.setText("");
        fila3.add(b30, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        b31 = new JButton();
        b31.setEnabled(true);
        Font b31Font = this.$$$getFont$$$(null, -1, -1, b31.getFont());
        if (b31Font != null) b31.setFont(b31Font);
        b31.setHideActionText(false);
        b31.setHorizontalTextPosition(0);
        b31.setText("");
        fila3.add(b31, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        b32 = new JButton();
        b32.setEnabled(true);
        Font b32Font = this.$$$getFont$$$(null, -1, -1, b32.getFont());
        if (b32Font != null) b32.setFont(b32Font);
        b32.setHideActionText(false);
        b32.setHorizontalTextPosition(0);
        b32.setText("");
        fila3.add(b32, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        b33 = new JButton();
        b33.setEnabled(true);
        Font b33Font = this.$$$getFont$$$(null, -1, -1, b33.getFont());
        if (b33Font != null) b33.setFont(b33Font);
        b33.setHideActionText(false);
        b33.setHorizontalTextPosition(0);
        b33.setText("");
        fila3.add(b33, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        fila4 = new JPanel();
        fila4.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 4, new Insets(0, 20, 0, 20), -1, -1));
        fila4.setEnabled(true);
        playerPanel.add(fila4, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        b40 = new JButton();
        b40.setEnabled(true);
        Font b40Font = this.$$$getFont$$$(null, -1, -1, b40.getFont());
        if (b40Font != null) b40.setFont(b40Font);
        b40.setHideActionText(false);
        b40.setHorizontalTextPosition(0);
        b40.setText("");
        fila4.add(b40, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        b41 = new JButton();
        b41.setEnabled(true);
        Font b41Font = this.$$$getFont$$$(null, -1, -1, b41.getFont());
        if (b41Font != null) b41.setFont(b41Font);
        b41.setHideActionText(false);
        b41.setHorizontalTextPosition(0);
        b41.setText("");
        fila4.add(b41, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        b42 = new JButton();
        b42.setEnabled(true);
        Font b42Font = this.$$$getFont$$$(null, -1, -1, b42.getFont());
        if (b42Font != null) b42.setFont(b42Font);
        b42.setHideActionText(false);
        b42.setHorizontalTextPosition(0);
        b42.setText("");
        fila4.add(b42, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        b43 = new JButton();
        b43.setEnabled(true);
        Font b43Font = this.$$$getFont$$$(null, -1, -1, b43.getFont());
        if (b43Font != null) b43.setFont(b43Font);
        b43.setHideActionText(false);
        b43.setHorizontalTextPosition(0);
        b43.setText("");
        fila4.add(b43, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        fila5 = new JPanel();
        fila5.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 4, new Insets(0, 20, 0, 20), -1, -1));
        fila5.setEnabled(true);
        playerPanel.add(fila5, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        b50 = new JButton();
        b50.setEnabled(true);
        Font b50Font = this.$$$getFont$$$(null, -1, -1, b50.getFont());
        if (b50Font != null) b50.setFont(b50Font);
        b50.setHideActionText(false);
        b50.setHorizontalTextPosition(0);
        b50.setText("");
        fila5.add(b50, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        b51 = new JButton();
        b51.setEnabled(true);
        Font b51Font = this.$$$getFont$$$(null, -1, -1, b51.getFont());
        if (b51Font != null) b51.setFont(b51Font);
        b51.setHideActionText(false);
        b51.setHorizontalTextPosition(0);
        b51.setText("");
        fila5.add(b51, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        b52 = new JButton();
        b52.setEnabled(true);
        Font b52Font = this.$$$getFont$$$(null, -1, -1, b52.getFont());
        if (b52Font != null) b52.setFont(b52Font);
        b52.setHideActionText(false);
        b52.setHorizontalTextPosition(0);
        b52.setText("");
        fila5.add(b52, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        b53 = new JButton();
        b53.setEnabled(true);
        Font b53Font = this.$$$getFont$$$(null, -1, -1, b53.getFont());
        if (b53Font != null) b53.setFont(b53Font);
        b53.setHideActionText(false);
        b53.setHorizontalTextPosition(0);
        b53.setText("");
        fila5.add(b53, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        fila6 = new JPanel();
        fila6.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 4, new Insets(0, 20, 0, 20), -1, -1));
        fila6.setEnabled(true);
        playerPanel.add(fila6, new com.intellij.uiDesigner.core.GridConstraints(6, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        b60 = new JButton();
        b60.setEnabled(true);
        Font b60Font = this.$$$getFont$$$(null, -1, -1, b60.getFont());
        if (b60Font != null) b60.setFont(b60Font);
        b60.setHideActionText(false);
        b60.setHorizontalTextPosition(0);
        b60.setText("");
        fila6.add(b60, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        b61 = new JButton();
        b61.setEnabled(true);
        Font b61Font = this.$$$getFont$$$(null, -1, -1, b61.getFont());
        if (b61Font != null) b61.setFont(b61Font);
        b61.setHideActionText(false);
        b61.setHorizontalTextPosition(0);
        b61.setText("");
        fila6.add(b61, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        b62 = new JButton();
        b62.setEnabled(true);
        Font b62Font = this.$$$getFont$$$(null, -1, -1, b62.getFont());
        if (b62Font != null) b62.setFont(b62Font);
        b62.setHideActionText(false);
        b62.setHorizontalTextPosition(0);
        b62.setText("");
        fila6.add(b62, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        b63 = new JButton();
        b63.setEnabled(true);
        Font b63Font = this.$$$getFont$$$(null, -1, -1, b63.getFont());
        if (b63Font != null) b63.setFont(b63Font);
        b63.setHideActionText(false);
        b63.setHorizontalTextPosition(0);
        b63.setText("");
        fila6.add(b63, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(0, 0), new Dimension(40, 40), new Dimension(40, 40), 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer3 = new com.intellij.uiDesigner.core.Spacer();
        playerPanel.add(spacer3, new com.intellij.uiDesigner.core.GridConstraints(7, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }
}
